feat: Equal is now capable of comparing an object to a specified type
FrecherxDachs/SmartMvvm.Xaml pull request #1
Opened 2021-11-23 16:37 UTC by IbexPeak

Now the Equal Markup is capable if comparing an object to a given type. The type must be provided as second parameter.

This can be used like this:
```
<ListBox x:Name="ListBox">
            <system:String>A string</system:String>
            <system:Int32>5</system:Int32>
            <system:Double>6.5</system:Double>
        </ListBox>
        <TextBlock Text="{If {Equal {Binding ElementName=ListBox, Path=SelectedItem}, {x:Type system:String}},
         Then='A string is selected',
         Else='An int is selected'}" />
```

2021-11-25 20:16 UTC, MichaeIDietrich commented
Adding special handling for type checking to the `Equal` markup extension seems like hidden magic that is not clear by the extension name. I would suggest to bring this logic to its own markup extension. 
Maybe something like: `{HasType {Bindind}, {x:Type xyz}}` or `{IsTypeOf {Bindind}, {x:Type xyz}}`

2021-11-25 20:55 UTC, IbexPeak commented
Thanks for the feedback. I moved the logic to a new markup "IsTypeOf".

2022-01-04 11:52 UTC, MichaeIDietrich requested changes

2022-01-04 11:52 UTC, MichaeIDietrich commented on src/SmartMvvm.Xaml/Markup/Logic/IsTypeOf.cs
> +    ///     Represents a markup extension that checks if a given object is equal to a given type.
The XML comment formatting is still different to the existing code.

2022-01-04 11:52 UTC, MichaeIDietrich commented on src/SmartMvvm.Xaml/Markup/Logic/IsTypeOf.cs
> +            : base(left, right, null)
The `null` parameter is not used in `Evaluate` so it can be dropped.

2022-01-04 11:52 UTC, MichaeIDietrich commented on src/SmartMvvm.Xaml/Markup/Logic/IsTypeOf.cs
> +            catch when (FallbackValue != DependencyProperty.UnsetValue)
I don't see where this code can throw an exception. We can remove this.

2022-01-04 11:52 UTC, MichaeIDietrich commented on src/SmartMvvm.Xaml/Markup/Logic/IsTypeOf.cs
> +        public IsTypeOf(object left, Type right)
Just for clarification how the `LogicalBase` base class works.
It is possible to freely nest these markup extensions in each other e.g. `{And {Or {Binding}, {Bool False}}, {Bool True}}` but it only works, if the constructor uses `object` as parameter type else the XAML parsing will fail. If you are not interested in such nesting you can use normal properties and fields like for `FallbackValue`.

2022-01-15 08:40 UTC, IbexPeak commented on src/SmartMvvm.Xaml/Markup/Logic/IsTypeOf.cs
> +    ///     Represents a markup extension that checks if a given object is equal to a given type.
Fixed

2022-01-15 08:40 UTC, IbexPeak commented on src/SmartMvvm.Xaml/Markup/Logic/IsTypeOf.cs
> +            : base(left, right, null)
Removed

2022-01-15 08:40 UTC, IbexPeak commented on src/SmartMvvm.Xaml/Markup/Logic/IsTypeOf.cs
> +            catch when (FallbackValue != DependencyProperty.UnsetValue)
Removed. Also removed FallbackValue.

2022-01-15 08:41 UTC, IbexPeak commented on src/SmartMvvm.Xaml/Markup/Logic/IsTypeOf.cs
> +        public IsTypeOf(object left, Type right)
Nesting should be possible, for thus I changed the parameter to object.

2022-01-15 08:42 UTC, IbexPeak commented
I have added another tab in the sample project with the above mentioned xaml code.

2022-01-24 19:08 UTC, MichaeIDietrich approved these changes

2022-01-24 19:09 UTC, merged